// Generated by CoffeeScript 1.6.2
(function() {
  safari.application.addEventListener("validate", function(event) {
    if (event.command === "flipIt") {
      return event.target.disabled = safari.application.activeBrowserWindow.activeTab.url == null;
    }
  });


  safari.application.addEventListener("command", function(event) {
    var activeBrowserWindow, currentTime, shareUrl, title, url;

    if (event.command === "flipIt") {
      activeBrowserWindow = safari.application.activeBrowserWindow;
      url = activeBrowserWindow.activeTab.url;
      title = activeBrowserWindow.activeTab.title;
      content = safari.application.activeBrowserWindow.activeTab.page;
      currentTime = new Date().getTime();

      shareUrl = "https://share.flipboard.com/bookmarklet/popout?v=2.0" + "&title=" + encodeURIComponent(title) + "&url=" + encodeURIComponent(url);
      tab = safari.application.openBrowserWindow().activeTab;

      return tab.url = shareUrl;
      
    }
  });

}).call(this);


